Modularize explore
NationalGenomicsInfrastructure/anglerfish pull request #91
Opened 2024-09-09 09:09 UTC by alneberg

I wanted to split up the explore command in smaller parts. I also wanted to write tests for the explore command. I had to introduce an ugly `_run_explore` command to enable testing on the top level. 

I also changed the Adaptor class since I found it confusing that the Adaptor class was initiated with an adaptors dictionary.

The name-change adaptor -> adapter will come in a later PR.

2024-09-12 15:01 UTC, remiolsen commented on anglerfish/explore/explore.py
> +def _run_explore(
Why the underscore (_) prefix?

2024-09-12 15:04 UTC, remiolsen commented on anglerfish/explore/explore.py
> +def _run_explore(
Sorry that this is a stupid question, but If this is so ugly what would you do differently if you could?

2024-09-12 15:04 UTC, remiolsen approved these changes

2024-09-13 08:12 UTC, alneberg commented on anglerfish/explore/explore.py
> +def _run_explore(
To differentiate it from  `run_explore` that calls this one... Not very nice

2024-09-13 08:14 UTC, alneberg commented on anglerfish/explore/explore.py
> +def _run_explore(
Yes, I don't think I explored the options very much. I think it was mainly the return values form the function that I was looking to use for testing. But thinking about it again it should be possible to test the original function as well, checking the results in the temporary directory... What do you think?

2024-09-13 09:05 UTC, remiolsen commented on anglerfish/explore/explore.py
> +def _run_explore(
I think I instinctively reacted because this has a specfic pythonic meaning. Had to look it up from pep8 

>_single_leading_underscore: weak “internal use” indicator. E.g. from M import * does not import objects whose names start with an underscore.

2024-09-13 09:09 UTC, alneberg commented on anglerfish/explore/explore.py
> +def _run_explore(
Yes, I'm aware. It's sort of true. It is supposed to be called by the main `run_explore` and not really by anything else (besides tests)

2024-09-13 09:11 UTC, remiolsen commented on anglerfish/explore/explore.py
> +def _run_explore(
That might be even messier on the testing side, but I don't have many legs to stand on when arguing for that. I think maybe the naming is my main problem. `def get_explore_results` maybe? Eventually you can split each separate task into functions (writing files, parsing alignments, etc.)

2024-09-13 09:12 UTC, alneberg commented on anglerfish/explore/explore.py
> +def _run_explore(
Yes I would be perfectly fine with renaming it. 👍

2024-09-13 09:19 UTC, remiolsen requested changes
Rename `_run_explore` function

2024-09-13 09:20 UTC, remiolsen commented on anglerfish/explore/explore.py
> +def _run_explore(
True. Aslo I guess that is not a very nice way of doing imports 🤷

2024-09-16 12:51 UTC, remiolsen approved these changes

2025-02-18 09:30 UTC, merged